<?php

declare(strict_types=1);

namespace App\AI;

/**
 * Deterministic, no-API-key-required InterpretationProvider for development and testing.
 * Every field is derived directly from the given context's own canonical text — it never
 * invents content, but it is also NOT a real interpretation: practicalReflection and
 * uncertainties say so explicitly. Never present this provider's output as AI-generated
 * insight; swap in a real InterpretationProvider for that.
 */
final class MockInterpretationProvider implements InterpretationProvider
{
    public function interpret(
        InterpretationContext $context,
        InterpretationLens $lens,
        InterpretationProfile $profile,
    ): Interpretation {
        $hasChangingLines = $context->changingLinePositions !== [];

        $uncertainties = [
            'Generated by a deterministic mock provider (App\\AI\\MockInterpretationProvider), '
                . 'not an AI model — treat this output as a pipeline placeholder, not guidance.',
        ];

        if ($lens !== InterpretationLens::General) {
            $uncertainties[] = sprintf(
                'Requested lens: %s — the mock provider does not vary its interpretation by lens.',
                $lens->value,
            );
        }

        if (!$profile->isDefault()) {
            $uncertainties[] = sprintf(
                'Active interpretation profile: tone=%s, length=%s%s — the mock provider does not '
                    . 'vary its interpretation by profile.',
                $profile->tone->value,
                $profile->length->value,
                $profile->notes !== null ? ', notes set' : '',
            );
        }

        return new Interpretation(
            summary: sprintf(
                'Hexagram %d (%s, %s) in response to: "%s"',
                $context->primaryHexagram->kingWenNumber,
                $context->primaryHexagram->chineseName,
                $context->primaryHexagram->pinyin,
                $context->question,
            ),
            coreTheme: $context->primaryHexagram->judgment,
            situation: $context->primaryHexagram->image,
            changingLineMeaning: $hasChangingLines
                ? implode(' ', $context->changingLineStatements)
                : null,
            transition: $hasChangingLines
                ? sprintf(
                    'Moving toward hexagram %d (%s, %s).',
                    $context->resultingHexagram->kingWenNumber,
                    $context->resultingHexagram->chineseName,
                    $context->resultingHexagram->pinyin,
                )
                : null,
            practicalReflection: 'This is a placeholder reflection from the mock interpretation '
                . 'provider, assembled directly from the canonical text above — it is not a '
                . 'real AI-generated interpretation.',
            uncertainties: $uncertainties,
            sourceReferences: $context->defaultSourceReferences(),
        );
    }

    /**
     * @param list<ConversationExchange> $history
     */
    public function answerFollowUp(
        InterpretationContext $context,
        array $history,
        string $question,
        InterpretationProfile $profile,
    ): FollowUpAnswer {
        $answer = sprintf(
            'This is a placeholder answer from the mock interpretation provider. Your '
                . 'question was: "%s" — it does not have real understanding of this '
                . 'conversation.',
            $question,
        );

        if (!$profile->isDefault()) {
            $answer .= sprintf(
                ' (Active interpretation profile: tone=%s, length=%s%s — not applied, since the '
                    . 'mock provider does not vary by profile.)',
                $profile->tone->value,
                $profile->length->value,
                $profile->notes !== null ? ', notes set' : '',
            );
        }

        return new FollowUpAnswer($answer, $context->defaultSourceReferences());
    }
}
