import { describe, it, expect, vi, afterEach } from 'vitest'
import { requestInterpretation } from './api'
import type { Interpretation } from './model'

const sample: Interpretation = {
  summary: 'Hexagram 1 in response to: "Should I take the offer?"',
  coreTheme: 'Khien represents what is great and originating.',
  situation: 'Heaven, in its motion, gives the idea of strength.',
  changingLineMeaning: 'The dragon lying hid in the deep.',
  transition: 'Moving toward hexagram 44.',
  practicalReflection: 'This is a placeholder reflection.',
  uncertainties: ['Generated by a mock provider.'],
  sourceReferences: ['Hexagram 1 judgment (Legge, 1899)'],
  lens: 'general',
}

describe('requestInterpretation', () => {
  afterEach(() => {
    vi.unstubAllGlobals()
  })

  it('posts to /interpretations/{id} and resolves the interpretation', async () => {
    const fetchMock = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(sample),
    })
    vi.stubGlobal('fetch', fetchMock)

    const result = await requestInterpretation('abc-123')

    expect(result).toEqual(sample)
    expect(fetchMock).toHaveBeenCalledWith(
      '/api/interpretations/abc-123',
      expect.objectContaining({ method: 'POST', body: JSON.stringify({}) }),
    )
  })

  it('posts the lens when one is given', async () => {
    const fetchMock = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ ...sample, lens: 'psychological' }),
    })
    vi.stubGlobal('fetch', fetchMock)

    const result = await requestInterpretation('abc-123', 'psychological')

    expect(result.lens).toBe('psychological')
    expect(fetchMock).toHaveBeenCalledWith(
      '/api/interpretations/abc-123',
      expect.objectContaining({ method: 'POST', body: JSON.stringify({ lens: 'psychological' }) }),
    )
  })
})
