import { describe, it, expect, vi, beforeEach } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import ConsultationPage from './ConsultationPage.vue'
import {
  fetchConsultation,
  updateConsultation,
  setReflectionReminder,
  clearReflectionReminder,
} from '../../entities/consultation/api'
import { fetchHexagram } from '../../entities/hexagram/api'
import { requestFollowUp, requestInterpretation } from '../../entities/interpretation/api'
import { ApiError } from '../../shared/api/http'
import type { ConsultationDetail } from '../../entities/consultation/model'
import type { Hexagram } from '../../entities/hexagram/model'
import type { Interpretation } from '../../entities/interpretation/model'

vi.mock('../../entities/consultation/api', () => ({
  fetchConsultation: vi.fn(),
  updateConsultation: vi.fn(),
  setReflectionReminder: vi.fn(),
  clearReflectionReminder: vi.fn(),
}))

vi.mock('../../entities/hexagram/api', () => ({
  fetchHexagram: vi.fn(),
}))

vi.mock('../../entities/interpretation/api', () => ({
  requestInterpretation: vi.fn(),
  requestFollowUp: vi.fn(),
}))

vi.mock('vue-router', () => ({
  useRoute: () => ({ params: { id: 'abc-123' } }),
}))

const stubs = { RouterLink: { template: '<a><slot /></a>' } }

function sampleHexagram(kingWenNumber: number): Hexagram {
  return {
    kingWenNumber,
    chineseName: '乾',
    pinyin: 'Qián',
    symbol: '䷀',
    lines: Array.from({ length: 6 }, (_, i) => ({
      position: i + 1,
      polarity: 'yang' as const,
    })),
    upperTrigram: { id: 'Qian', name: 'Qian', chineseName: '乾', pinyin: 'Qián', symbol: '☰' },
    lowerTrigram: { id: 'Qian', name: 'Qian', chineseName: '乾', pinyin: 'Qián', symbol: '☰' },
    judgment: null,
    image: null,
    lineStatements: null,
    relationships: {
      nuclear: { kingWenNumber, chineseName: '乾', pinyin: 'Qián' },
      reversed: { kingWenNumber, chineseName: '乾', pinyin: 'Qián' },
      complement: { kingWenNumber, chineseName: '乾', pinyin: 'Qián' },
    },
    favorite: false,
  }
}

const sampleConsultation: ConsultationDetail = {
  id: 'abc-123',
  question: 'Should I take the offer?',
  method: 'three_coins',
  primaryHexagram: { kingWenNumber: 1, chineseName: '乾', pinyin: 'Qián' },
  changingLinePositions: [1],
  resultingHexagram: { kingWenNumber: 44, chineseName: '姤', pinyin: 'Gòu' },
  createdAt: '2026-08-14T10:00:00+00:00',
  notes: [{ label: 'before', text: 'Nervous.', createdAt: '2026-08-14T09:00:00+00:00' }],
  tags: ['career'],
  context: null,
  whatHappenedBefore: null,
  whatUserWantsToUnderstand: null,
  backgroundInformation: null,
  initialInterpretation: null,
  outcome: null,
  followUpTo: null,
  followUps: [],
  favorite: false,
  repeats: { primaryHexagram: [], resultingHexagram: [], changingLines: [] },
  readingGuidance: { changingLineCount: 0, rule: 'no-changing-lines', refs: [], specialText: null },
  reminder: null,
}

const sampleInterpretation: Interpretation = {
  summary: 'Hexagram 1 in response to: "Should I take the offer?"',
  coreTheme: 'Khien represents what is great and originating.',
  situation: 'Heaven, in its motion, gives the idea of strength.',
  changingLineMeaning: 'The dragon lying hid in the deep.',
  transition: 'Moving toward hexagram 44.',
  practicalReflection: 'This is a placeholder reflection.',
  uncertainties: ['Generated by a mock provider.'],
  sourceReferences: ['Hexagram 1 judgment (Legge, 1899)'],
  lens: 'general',
  language: 'en',
}

function interpretationButton(wrapper: ReturnType<typeof mount>) {
  return wrapper.findAll('button').find((b) => b.text().includes('Get Interpretation'))!
}

function followUpForm(wrapper: ReturnType<typeof mount>) {
  return wrapper.findAll('form').find((f) => f.text().includes('Ask'))!
}

describe('ConsultationPage', () => {
  beforeEach(() => {
    vi.mocked(requestInterpretation).mockClear()
    vi.mocked(requestFollowUp).mockClear()
    vi.mocked(updateConsultation).mockClear()
    vi.mocked(setReflectionReminder).mockReset().mockResolvedValue({ remindAt: '2026-09-15T00:00:00+00:00' })
    vi.mocked(clearReflectionReminder).mockReset().mockResolvedValue(undefined)
  })

  it('renders the consultation with both hexagram diagrams and marks changing lines', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).toContain('Should I take the offer?')
    expect(wrapper.text()).toContain('Nervous.')
    expect(wrapper.text()).toContain('career')
    expect(wrapper.find('[data-position="1"][data-changing="true"]').exists()).toBe(true)
  })

  it('links to the hexagram comparison page for its primary/resulting pair', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const compareLink = wrapper.findAll('a').find((a) => a.text() === 'Compare hexagrams')
    expect(compareLink).toBeDefined()
    expect(compareLink!.attributes('to')).toBe('/hexagrams/compare?a=1&b=44')
  })

  it('shows a working "Create Follow-up" link', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const createFollowUpLink = wrapper.findAll('a').find((a) => a.text() === 'Create Follow-up')
    expect(createFollowUpLink).toBeDefined()
    expect(createFollowUpLink!.attributes('to')).toBe('/consultations/new?followUpTo=abc-123')
  })

  it('shows the follow-up-to link when set', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      followUpTo: { id: 'original-id', question: 'Original question?' },
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).toContain('Follow-up to:')
    const link = wrapper.findAll('a').find((a) => a.text() === 'Original question?')
    expect(link).toBeDefined()
    expect(link!.attributes('to')).toBe('/consultations/original-id')
  })

  it('has no follow-up-to text when unset', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).not.toContain('Follow-up to:')
  })

  it('lists follow-ups linking to each', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      followUps: [
        { id: 'follow-up-1', question: 'First follow-up?' },
        { id: 'follow-up-2', question: 'Second follow-up?' },
      ],
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).toContain('Follow-ups')
    const firstLink = wrapper.findAll('a').find((a) => a.text() === 'First follow-up?')
    const secondLink = wrapper.findAll('a').find((a) => a.text() === 'Second follow-up?')
    expect(firstLink!.attributes('to')).toBe('/consultations/follow-up-1')
    expect(secondLink!.attributes('to')).toBe('/consultations/follow-up-2')
  })

  it('renders each non-empty repeats category as a distinctly labeled linked list', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      repeats: {
        primaryHexagram: [{ id: 'p-1', question: 'Same primary before?' }],
        resultingHexagram: [{ id: 'r-1', question: 'Same resulting before?' }],
        changingLines: [{ id: 'c-1', question: 'Same changing lines before?' }],
      },
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).toContain('Same primary hexagram before')
    expect(wrapper.text()).toContain('Same resulting hexagram before')
    expect(wrapper.text()).toContain('Same changing lines before')

    const primaryLink = wrapper.findAll('a').find((a) => a.text() === 'Same primary before?')
    const resultingLink = wrapper.findAll('a').find((a) => a.text() === 'Same resulting before?')
    const changingLink = wrapper.findAll('a').find((a) => a.text() === 'Same changing lines before?')
    expect(primaryLink!.attributes('to')).toBe('/consultations/p-1')
    expect(resultingLink!.attributes('to')).toBe('/consultations/r-1')
    expect(changingLink!.attributes('to')).toBe('/consultations/c-1')
  })

  it('shows no repeats section at all when all three categories are empty', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).not.toContain('Same primary hexagram before')
    expect(wrapper.text()).not.toContain('Same resulting hexagram before')
    expect(wrapper.text()).not.toContain('Same changing lines before')
  })

  it('toggles favorite on and off via the toggle button', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(updateConsultation).mockResolvedValue({ ...sampleConsultation, favorite: true })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const button = wrapper.findAll('button').find((b) => b.text().includes('Add to Favorites'))!
    await button.trigger('click')
    await flushPromises()

    expect(updateConsultation).toHaveBeenCalledWith('abc-123', { favorite: true })
    expect(wrapper.text()).toContain('★ Favorited')
  })

  it('shows an inline error when toggling favorite fails, without disturbing the rest of the page', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(updateConsultation).mockRejectedValue(new Error('favorite toggle failed'))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const button = wrapper.findAll('button').find((b) => b.text().includes('Add to Favorites'))!
    await button.trigger('click')
    await flushPromises()

    expect(wrapper.text()).toContain('favorite toggle failed')
    expect(wrapper.text()).toContain('Should I take the offer?')
  })

  it('renders a working Print / Export button that calls window.print()', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    const printSpy = vi.spyOn(window, 'print').mockImplementation(() => {})

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const button = wrapper.findAll('button').find((b) => b.text() === 'Print / Export')!
    await button.trigger('click')

    expect(printSpy).toHaveBeenCalledOnce()
    printSpy.mockRestore()
  })

  it('marks the AI Interpretation section print-hidden until an interpretation has loaded', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(requestInterpretation).mockResolvedValue(sampleInterpretation)

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const section = wrapper.findAll('section').find((s) => s.text().includes('AI Interpretation'))!
    expect(section.classes()).toContain('print-hidden')

    await interpretationButton(wrapper).trigger('click')
    await flushPromises()

    expect(section.classes()).not.toContain('print-hidden')
  })

  it('shows a working "View Public Share Page" link to the share route', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const link = wrapper.findAll('a').find((a) => a.text() === 'View Public Share Page')
    expect(link).toBeDefined()
    expect(link!.attributes('to')).toBe('/share/consultations/abc-123')
  })

  it('copies the share link to the clipboard', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    const writeText = vi.fn().mockResolvedValue(undefined)
    Object.assign(navigator, { clipboard: { writeText } })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const button = wrapper.findAll('button').find((b) => b.text() === 'Copy Share Link')!
    await button.trigger('click')
    await flushPromises()

    expect(writeText).toHaveBeenCalledWith(expect.stringContaining('/share/consultations/abc-123'))
    expect(wrapper.text()).toContain('Link Copied')
  })

  it('shows an inline error when copying the share link fails', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    Object.assign(navigator, {
      clipboard: { writeText: vi.fn().mockRejectedValue(new Error('clipboard denied')) },
    })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const button = wrapper.findAll('button').find((b) => b.text() === 'Copy Share Link')!
    await button.trigger('click')
    await flushPromises()

    expect(wrapper.text()).toContain('clipboard denied')
  })

  it('copies the consultation as Markdown to the clipboard', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    const writeText = vi.fn().mockResolvedValue(undefined)
    Object.assign(navigator, { clipboard: { writeText } })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const button = wrapper.findAll('button').find((b) => b.text() === 'Copy as Markdown')!
    await button.trigger('click')
    await flushPromises()

    expect(writeText).toHaveBeenCalledWith(expect.stringContaining(`# ${sampleConsultation.question}`))
  })

  it('shows an inline error when copying Markdown fails', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    Object.assign(navigator, {
      clipboard: { writeText: vi.fn().mockRejectedValue(new Error('nope')) },
    })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await wrapper.findAll('button').find((b) => b.text() === 'Copy as Markdown')!.trigger('click')
    await flushPromises()

    expect(wrapper.text()).toContain('Failed to copy Markdown.')
  })

  it('downloads the consultation as a .md file', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    const createObjectURL = vi.fn().mockReturnValue('blob:md')
    const revokeObjectURL = vi.fn()
    Object.assign(URL, { createObjectURL, revokeObjectURL })
    const clickSpy = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await wrapper.findAll('button').find((b) => b.text() === 'Download .md')!.trigger('click')

    expect(createObjectURL).toHaveBeenCalled()
    expect(clickSpy).toHaveBeenCalled()
    clickSpy.mockRestore()
  })

  it('pre-fills the context form from the loaded consultation', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      context: 'Existing context.',
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const textarea = wrapper.find('#edit-context').element as HTMLTextAreaElement
    expect(textarea.value).toBe('Existing context.')
  })

  it('saves the context form and updates the page in place', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(updateConsultation).mockResolvedValue({
      ...sampleConsultation,
      context: 'New context.',
    })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await wrapper.find('#edit-context').setValue('New context.')
    const contextForm = wrapper.findAll('form')[2]!
    await contextForm.trigger('submit')
    await flushPromises()

    expect(updateConsultation).toHaveBeenCalledWith('abc-123', {
      context: 'New context.',
      whatHappenedBefore: null,
      whatUserWantsToUnderstand: null,
      backgroundInformation: null,
      initialInterpretation: null,
    })
    const textarea = wrapper.find('#edit-context').element as HTMLTextAreaElement
    expect(textarea.value).toBe('New context.')
  })

  it('shows an inline error when saving context fails, without disturbing the rest of the page', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(updateConsultation).mockRejectedValue(new Error('context save failed'))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await wrapper.find('#edit-context').setValue('New context.')
    const contextForm = wrapper.findAll('form')[2]!
    await contextForm.trigger('submit')
    await flushPromises()

    expect(wrapper.text()).toContain('context save failed')
    expect(wrapper.text()).toContain('Should I take the offer?')
  })

  it('pre-fills the outcome form from the loaded consultation', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      outcome: {
        whatActuallyHappened: 'Took the offer.',
        outcome: 'Going well.',
        reflection: null,
        recordedAt: '2026-08-20T09:00:00+00:00',
        interpretationLens: null,
        interpretationSummary: null,
      },
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const whatHappened = wrapper.find('#edit-what-happened').element as HTMLTextAreaElement
    const outcomeField = wrapper.find('#edit-outcome').element as HTMLTextAreaElement
    const reflection = wrapper.find('#edit-reflection').element as HTMLTextAreaElement
    expect(whatHappened.value).toBe('Took the offer.')
    expect(outcomeField.value).toBe('Going well.')
    expect(reflection.value).toBe('')
    expect(wrapper.text()).toContain('Last recorded')
  })

  it('has no outcome section content when nothing has been recorded yet', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).not.toContain('Last recorded')
  })

  it('saves the outcome form and updates the page in place', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(updateConsultation).mockResolvedValue({
      ...sampleConsultation,
      outcome: {
        whatActuallyHappened: 'Took the offer.',
        outcome: null,
        reflection: null,
        recordedAt: '2026-08-20T09:00:00+00:00',
        interpretationLens: null,
        interpretationSummary: null,
      },
    })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await wrapper.find('#edit-what-happened').setValue('Took the offer.')
    const outcomeForm = wrapper.findAll('form')[3]!
    await outcomeForm.trigger('submit')
    await flushPromises()

    expect(updateConsultation).toHaveBeenCalledWith('abc-123', {
      whatActuallyHappened: 'Took the offer.',
      outcome: null,
      reflection: null,
      interpretationLens: null,
      interpretationSummary: null,
    })
    expect(wrapper.text()).toContain('Last recorded')
  })

  it('shows an inline error when saving the outcome fails, without disturbing the rest of the page', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(updateConsultation).mockRejectedValue(new Error('outcome save failed'))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await wrapper.find('#edit-what-happened').setValue('Took the offer.')
    const outcomeForm = wrapper.findAll('form')[3]!
    await outcomeForm.trigger('submit')
    await flushPromises()

    expect(wrapper.text()).toContain('outcome save failed')
    expect(wrapper.text()).toContain('Should I take the offer?')
  })

  it('shows "No changing lines" when there are none', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      changingLinePositions: [],
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).toContain('No changing lines')
  })

  it('shows the reading-guidance panel with the rule sentence and the governing line text', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      readingGuidance: {
        changingLineCount: 2,
        rule: 'two-changing-lines',
        refs: [
          { hexagram: 'primary', kind: 'line', position: 2, governing: false, text: 'Lower line text.' },
          { hexagram: 'primary', kind: 'line', position: 5, governing: true, text: 'Upper line text.' },
        ],
        specialText: null,
      },
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).toContain('How to read this cast')
    expect(wrapper.text()).toContain('the upper line governs')
    expect(wrapper.text()).toContain('Upper line text.')
    expect(wrapper.text()).toContain('Lower line text.')
    expect(wrapper.find('.reading-ref-governing').text()).toContain('Upper line text.')
  })

  it('shows the "Use Nine" special text when all six lines change on Qian', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      readingGuidance: {
        changingLineCount: 6,
        rule: 'six-changing-lines',
        refs: [],
        specialText: 'use-nine',
        specialTextContent: 'The use of the number NINE …',
      },
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).toContain('Use Nine')
    expect(wrapper.text()).toContain('The use of the number NINE')
  })

  it('shows a not-found state on a 404', async () => {
    vi.mocked(fetchConsultation).mockRejectedValue(new ApiError(404, 'Not Found'))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text().toLowerCase()).toContain('not found')
  })

  it('shows a generic error state for other failures', async () => {
    vi.mocked(fetchConsultation).mockRejectedValue(new Error('network down'))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).toContain('network down')
  })

  it('does not request an interpretation until the button is clicked', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(requestInterpretation).not.toHaveBeenCalled()
  })

  it('requests and renders an interpretation on click', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(requestInterpretation).mockResolvedValue(sampleInterpretation)

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await interpretationButton(wrapper).trigger('click')
    await flushPromises()

    expect(requestInterpretation).toHaveBeenCalledWith('abc-123', 'general', 'en')
    expect(wrapper.text()).toContain('Khien represents what is great and originating.')
    expect(wrapper.text()).toContain('The dragon lying hid in the deep.')
    expect(wrapper.text()).toContain('Hexagram 1 judgment (Legge, 1899)')
  })

  it('links an interpretation to the (unsaved) outcome form, and persists it on save', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(requestInterpretation).mockResolvedValue(sampleInterpretation)
    vi.mocked(updateConsultation).mockResolvedValue({
      ...sampleConsultation,
      outcome: {
        whatActuallyHappened: null,
        outcome: null,
        reflection: null,
        recordedAt: '2026-08-21T09:00:00+00:00',
        interpretationLens: 'general',
        interpretationSummary: sampleInterpretation.summary,
      },
    })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()
    await interpretationButton(wrapper).trigger('click')
    await flushPromises()

    const linkButton = wrapper.findAll('button').find((b) => b.text() === 'Link to Outcome')!
    await linkButton.trigger('click')
    await flushPromises()

    expect(wrapper.text()).toContain(`Linked: general — ${sampleInterpretation.summary}`)

    const outcomeForm = wrapper.findAll('form')[3]!
    await outcomeForm.trigger('submit')
    await flushPromises()

    expect(updateConsultation).toHaveBeenCalledWith('abc-123', {
      whatActuallyHappened: null,
      outcome: null,
      reflection: null,
      interpretationLens: 'general',
      interpretationSummary: sampleInterpretation.summary,
    })
  })

  it('unlinks an interpretation from the (unsaved) outcome form', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      outcome: {
        whatActuallyHappened: 'Took the offer.',
        outcome: null,
        reflection: null,
        recordedAt: '2026-08-20T09:00:00+00:00',
        interpretationLens: 'practical',
        interpretationSummary: 'A previously linked summary.',
      },
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.text()).toContain('Linked: practical — A previously linked summary.')

    const unlinkButton = wrapper.findAll('button').find((b) => b.text() === 'Unlink')!
    await unlinkButton.trigger('click')
    await flushPromises()

    expect(wrapper.text()).not.toContain('Linked:')
  })

  it('omits changingLineMeaning/transition rows when they are null', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(requestInterpretation).mockResolvedValue({
      ...sampleInterpretation,
      changingLineMeaning: null,
      transition: null,
    })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()
    await interpretationButton(wrapper).trigger('click')
    await flushPromises()

    expect(wrapper.text()).not.toContain('Changing line meaning')
    expect(wrapper.text()).not.toContain('Transition')
  })

  it('shows an inline error without disturbing the rest of the page', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(requestInterpretation).mockRejectedValue(new Error('interpretation failed'))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()
    await interpretationButton(wrapper).trigger('click')
    await flushPromises()

    expect(wrapper.text()).toContain('interpretation failed')
    expect(wrapper.text()).toContain('Should I take the offer?')
  })

  it('renders a four-way lens selector, defaulting to General', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const lensButtons = wrapper.findAll('button[aria-pressed]')
    expect(lensButtons.map((b) => b.text().trim())).toEqual(['general', 'psychological', 'practical', 'symbolic'])
    expect(lensButtons[0]!.attributes('aria-pressed')).toBe('true')
  })

  it('requests each lens separately and caches results per lens, avoiding redundant requests', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(requestInterpretation).mockImplementation((_id, lens) =>
      Promise.resolve({ ...sampleInterpretation, lens: lens ?? 'general', summary: `Summary for ${lens}` }),
    )

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    function lensButton(text: string) {
      return wrapper.findAll('button[aria-pressed]').find((b) => b.text().includes(text))!
    }

    // Fetch "general" (the default).
    await interpretationButton(wrapper).trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('Summary for general')

    // Switch to "practical" and fetch it.
    await lensButton('practical').trigger('click')
    expect(requestInterpretation).toHaveBeenCalledTimes(1)
    await interpretationButton(wrapper).trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('Summary for practical')
    expect(requestInterpretation).toHaveBeenCalledTimes(2)

    // Switch back to "general" — already cached, no new request.
    await lensButton('general').trigger('click')
    expect(wrapper.text()).toContain('Summary for general')
    expect(requestInterpretation).toHaveBeenCalledTimes(2)
  })

  it('asks a follow-up question, appends it to the thread, and clears the form', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(requestInterpretation).mockResolvedValue(sampleInterpretation)
    vi.mocked(requestFollowUp).mockResolvedValue({ answer: 'Hold back for now.', sourceReferences: [] })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()
    await interpretationButton(wrapper).trigger('click')
    await flushPromises()

    await wrapper.find('textarea[placeholder="Ask a follow-up question…"]').setValue('What should I avoid?')
    await followUpForm(wrapper).trigger('submit')
    await flushPromises()

    expect(requestFollowUp).toHaveBeenCalledWith('abc-123', 'What should I avoid?', [], 'en')
    expect(wrapper.text()).toContain('What should I avoid?')
    expect(wrapper.text()).toContain('Hold back for now.')
    expect(
      (wrapper.find('textarea[placeholder="Ask a follow-up question…"]').element as HTMLTextAreaElement).value,
    ).toBe('')
  })

  it('sends prior exchanges as history on a second follow-up in the same lens', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(requestInterpretation).mockResolvedValue(sampleInterpretation)
    vi.mocked(requestFollowUp)
      .mockResolvedValueOnce({ answer: 'First answer.', sourceReferences: [] })
      .mockResolvedValueOnce({ answer: 'Second answer.', sourceReferences: [] })

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()
    await interpretationButton(wrapper).trigger('click')
    await flushPromises()

    const textarea = wrapper.find('textarea[placeholder="Ask a follow-up question…"]')

    await textarea.setValue('First question?')
    await followUpForm(wrapper).trigger('submit')
    await flushPromises()

    await textarea.setValue('Second question?')
    await followUpForm(wrapper).trigger('submit')
    await flushPromises()

    expect(requestFollowUp).toHaveBeenLastCalledWith(
      'abc-123',
      'Second question?',
      [{ question: 'First question?', answer: 'First answer.' }],
      'en',
    )
  })

  it('shows an inline error when a follow-up request fails', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(requestInterpretation).mockResolvedValue(sampleInterpretation)
    vi.mocked(requestFollowUp).mockRejectedValue(new Error('followup failed'))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()
    await interpretationButton(wrapper).trigger('click')
    await flushPromises()

    await wrapper.find('textarea[placeholder="Ask a follow-up question…"]').setValue('Q?')
    await followUpForm(wrapper).trigger('submit')
    await flushPromises()

    expect(wrapper.text()).toContain('followup failed')
  })

  it('adds a note and clears the form on success', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    const updated = {
      ...sampleConsultation,
      notes: [
        ...sampleConsultation.notes,
        { label: 'after' as const, text: 'Went well.', createdAt: '2026-08-14T11:00:00+00:00' },
      ],
    }
    vi.mocked(updateConsultation).mockResolvedValue(updated)

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await wrapper.find('textarea').setValue('Went well.')
    await wrapper.find('form').trigger('submit')
    await flushPromises()

    expect(updateConsultation).toHaveBeenCalledWith('abc-123', {
      note: { label: 'after', text: 'Went well.' },
    })
    expect(wrapper.text()).toContain('Went well.')
    expect((wrapper.find('textarea').element as HTMLTextAreaElement).value).toBe('')
  })

  it('shows an inline error when adding a note fails, without disturbing the rest of the page', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(updateConsultation).mockRejectedValue(new Error('note rejected'))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await wrapper.find('textarea').setValue('Bad note.')
    await wrapper.find('form').trigger('submit')
    await flushPromises()

    expect(wrapper.text()).toContain('note rejected')
    expect(wrapper.text()).toContain('Should I take the offer?')
  })

  it('adds a tag and clears the form on success', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    const updated = { ...sampleConsultation, tags: [...sampleConsultation.tags, 'clarity'] }
    vi.mocked(updateConsultation).mockResolvedValue(updated)

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const tagInput = wrapper.find('input[type="text"]')
    await tagInput.setValue('clarity')
    const tagForm = wrapper.findAll('form')[1]
    await tagForm.trigger('submit')
    await flushPromises()

    expect(updateConsultation).toHaveBeenCalledWith('abc-123', { tag: 'clarity' })
    expect(wrapper.text()).toContain('clarity')
    expect((tagInput.element as HTMLInputElement).value).toBe('')
  })

  it('shows an inline error when adding a tag fails, without disturbing the rest of the page', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))
    vi.mocked(updateConsultation).mockRejectedValue(new Error('tag rejected'))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    await wrapper.find('input[type="text"]').setValue('bad tag')
    const tagForm = wrapper.findAll('form')[1]
    await tagForm.trigger('submit')
    await flushPromises()

    expect(wrapper.text()).toContain('tag rejected')
    expect(wrapper.text()).toContain('Should I take the offer?')
  })

  it('sets a reflection reminder from the date input while there is no outcome', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue(sampleConsultation)
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    const dateInput = wrapper.find('#reflection-reminder')
    expect(dateInput.exists()).toBe(true)

    await dateInput.setValue('2026-09-15')
    const setButton = wrapper.findAll('button').find((b) => b.text() === 'Set reminder')!
    await setButton.trigger('click')
    await flushPromises()

    expect(setReflectionReminder).toHaveBeenCalledWith('abc-123', '2026-09-15')
    expect(wrapper.text()).toContain('Reminder set for')
  })

  it('hides the reflection reminder control once an outcome is recorded', async () => {
    vi.mocked(fetchConsultation).mockResolvedValue({
      ...sampleConsultation,
      outcome: {
        whatActuallyHappened: 'Took the job.',
        outcome: 'Good.',
        reflection: null,
        recordedAt: '2026-09-01T10:00:00+00:00',
        interpretationLens: null,
        interpretationSummary: null,
      },
    })
    vi.mocked(fetchHexagram).mockImplementation((n: number) => Promise.resolve(sampleHexagram(n)))

    const wrapper = mount(ConsultationPage, { global: { stubs } })
    await flushPromises()

    expect(wrapper.find('#reflection-reminder').exists()).toBe(false)
  })
})
